receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
